// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OregonTrail.Models;

#nullable disable

namespace OregonTrail.Migrations
{
    [DbContext(typeof(CaravanContext))]
    partial class CaravanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OregonTrail.Models.Caravan", b =>
                {
                    b.Property<int>("CaravanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaravanId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaravanId");

                    b.ToTable("Caravan");
                });

            modelBuilder.Entity("OregonTrail.Models.Passanger", b =>
                {
                    b.Property<int>("PassangerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassangerId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WagonId")
                        .HasColumnType("int");

                    b.HasKey("PassangerId");

                    b.HasIndex("WagonId");

                    b.ToTable("Passanger");
                });

            modelBuilder.Entity("OregonTrail.Models.Wagon", b =>
                {
                    b.Property<int>("WagonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WagonId"));

                    b.Property<int>("CaravanId")
                        .HasColumnType("int");

                    b.Property<bool>("Covered")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumWheels")
                        .HasColumnType("int");

                    b.HasKey("WagonId");

                    b.HasIndex("CaravanId");

                    b.ToTable("Wagon");
                });

            modelBuilder.Entity("OregonTrail.Models.Passanger", b =>
                {
                    b.HasOne("OregonTrail.Models.Wagon", "Wagon")
                        .WithMany("Passangers")
                        .HasForeignKey("WagonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wagon");
                });

            modelBuilder.Entity("OregonTrail.Models.Wagon", b =>
                {
                    b.HasOne("OregonTrail.Models.Caravan", "Caravan")
                        .WithMany("Wagons")
                        .HasForeignKey("CaravanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caravan");
                });

            modelBuilder.Entity("OregonTrail.Models.Caravan", b =>
                {
                    b.Navigation("Wagons");
                });

            modelBuilder.Entity("OregonTrail.Models.Wagon", b =>
                {
                    b.Navigation("Passangers");
                });
#pragma warning restore 612, 618
        }
    }
}
